//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blida()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_Blida { get; set; }
        public string Name_Blida { get; set; }
        public int Prica_Blide { get; set; }
        public int ID_Postavhik { get; set; }
    
        public virtual Postavhik Postavhik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
