//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        public int ID_Chek { get; set; }
        public int Number_of_Check { get; set; }
        public int ID_Sotrudnika { get; set; }
        public int ID_Zakaz { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
