//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SushiEntities1 : DbContext
    {
        public SushiEntities1()
            : base("name=SushiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Blida> Blida { get; set; }
        public virtual DbSet<Chek> Chek { get; set; }
        public virtual DbSet<Dolgnost> Dolgnost { get; set; }
        public virtual DbSet<Klinet> Klinet { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<Postavhik> Postavhik { get; set; }
        public virtual DbSet<Prikaz_o_Prieme> Prikaz_o_Prieme { get; set; }
        public virtual DbSet<Prikaz_ob_Ovolen> Prikaz_ob_Ovolen { get; set; }
        public virtual DbSet<Rezume> Rezume { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Soiskatel> Soiskatel { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
