//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavhik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavhik()
        {
            this.Blida = new HashSet<Blida>();
        }
    
        public int ID_Postavhik { get; set; }
        public string Familia_Postavhik { get; set; }
        public string Name_Postavhik { get; set; }
        public string Otchestvo_Postavik { get; set; }
        public string Seria_Document { get; set; }
        public string Nomer_Document { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blida> Blida { get; set; }
    }
}
