//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prikaz_o_Prieme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prikaz_o_Prieme()
        {
            this.Sotrudniki = new HashSet<Sotrudniki>();
        }
    
        public int ID_Prikaz_o_Prieme { get; set; }
        public int ID_Dolgnost { get; set; }
        public int ID_Soiskatel { get; set; }
    
        public virtual Dolgnost Dolgnost { get; set; }
        public virtual Soiskatel Soiskatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki> Sotrudniki { get; set; }
    }
}
