//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prikaz_ob_Ovolen
    {
        public int ID_Prikaz_ob_Ovolen { get; set; }
        public int Nomer_Prikaz { get; set; }
        public string Prichina { get; set; }
        public int ID_Sotrudnika { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
