//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezume
    {
        public int ID_Rezume { get; set; }
        public int ID_Soiskatel { get; set; }
        public string Cel { get; set; }
        public string Obrazovanii { get; set; }
        public string Opit_Raboti { get; set; }
        public string Proff_Naviki { get; set; }
    
        public virtual Soiskatel Soiskatel { get; set; }
    }
}
