//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soiskatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soiskatel()
        {
            this.Prikaz_o_Prieme = new HashSet<Prikaz_o_Prieme>();
            this.Rezume = new HashSet<Rezume>();
        }
    
        public int ID_Soiskatel { get; set; }
        public string Familia_Soiskatel { get; set; }
        public string Name_Soiskatel { get; set; }
        public string Otchestvo_Soiskatel { get; set; }
        public string Seria_Document { get; set; }
        public string Nomer_Document { get; set; }
        public string Data_Rojdrnia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prikaz_o_Prieme> Prikaz_o_Prieme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezume> Rezume { get; set; }
    }
}
