//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Shop.del
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Chek = new HashSet<Chek>();
            this.Prikaz_ob_Ovolen = new HashSet<Prikaz_ob_Ovolen>();
        }
    
        public int ID_Sotrudnika { get; set; }
        public string Familia_Sotrudnika { get; set; }
        public string Name_Sotrudnika { get; set; }
        public string Otchestvo_Sotrudnika { get; set; }
        public string Seria_Document { get; set; }
        public string Number_Document { get; set; }
        public int ID_Dolgnost { get; set; }
        public int ID_Authorization { get; set; }
        public int ID_Prikaz_o_Prieme { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chek> Chek { get; set; }
        public virtual Dolgnost Dolgnost { get; set; }
        public virtual Prikaz_o_Prieme Prikaz_o_Prieme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prikaz_ob_Ovolen> Prikaz_ob_Ovolen { get; set; }
    }
}
